const result = document.querySelector(".result");
result.innerHTML = "";

const one = document.querySelector(".one");
one.addEventListener("click", () => (result.innerHTML += "1"));
const two = document.querySelector(".two");
two.addEventListener("click", () => (result.innerHTML += "2"));
const three = document.querySelector(".three");
three.addEventListener("click", () => (result.innerHTML += "3"));
const four = document.querySelector(".four");
four.addEventListener("click", () => (result.innerHTML += "4"));
const five = document.querySelector(".five");
five.addEventListener("click", () => (result.innerHTML += "5"));
const six = document.querySelector(".six");
six.addEventListener("click", () => (result.innerHTML += "6"));
const seven = document.querySelector(".seven");
seven.addEventListener("click", () => (result.innerHTML += "7"));
const eight = document.querySelector(".eight");
eight.addEventListener("click", () => (result.innerHTML += "8"));
const nine = document.querySelector(".nine");
nine.addEventListener("click", () => (result.innerHTML += "9"));
const zero = document.querySelector(".zero");
zero.addEventListener("click", () => (result.innerHTML += "0"));
